#' craft: A CRAFT Pipeline for Evaluating LLM-Generated Data
#'
#' Implements the five-step C-R-A-F-T framework (Construct, Report,
#' Assess, Field-audit, Translate) for evaluating data generated by
#' large language models in political and social science research.
#'
#' @section Step C - Construct role-task:
#' \code{\link{role}}
#'
#' @section Step R - Report dual-track metrics:
#' \code{\link{reliab}}, \code{\link{reliab_pairs}}, \code{\link{valid}},
#' \code{\link{dual}}
#'
#' @section Step A - Assess stability:
#' \code{\link{stab}}
#'
#' @section Step F - Field audit:
#' \code{\link{audit}}, \code{\link{disagree}}, \code{\link{tau_sens}}
#'
#' @section Step T - Translate to inference:
#' \code{\link{dsl_fit}}, \code{\link{dsl_cmp}}
#'
#' @section Report generation:
#' \code{\link{report}}
#'
#' @keywords internal
"_PACKAGE"
